title: Mediocre Blog
author: Brian Picciano
email: mediocregopher@gmail.com
description: >-
  A mix of tech, art, travel, and who knows what else.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.mediocregopher.com # the base hostname & protocol for your site, e.g. http://example.com
repository: mediocregopher/blog.mediocregopher.com
twitter_username: mediocre_gopher
github_username:  mediocregopher
rss: rss
highlighter: rouge

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

date_format: "%b %-d, %Y"

img_widths:
    - 500
    - 1000
    - 1500
    - 2000
    - 2500
    - 3000
